apiVersion: v1
kind: Service
metadata:
  name: approval-processing-service
  namespace: erp
spec:
  selector:
    app: approval-processing-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  - name: grpc
    port: 9091
    targetPort: 9091
