apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp-ingress
  namespace: erp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: erp.local
    http:
      paths:
      - path: /employees
        pathType: Prefix
        backend:
          service:
            name: employee-service
            port:
              number: 8080
      - path: /approvals
        pathType: Prefix
        backend:
          service:
            name: approval-request-service
            port:
              number: 8081
      - path: /process
        pathType: Prefix
        backend:
          service:
            name: approval-processing-service
            port:
              number: 8083
      - path: /internal/notification
        pathType: Prefix
        backend:
          service:
            name: notification-service
            port:
              number: 8082
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: notification-service
            port:
              number: 8082
